#注意 frontend和backend网络不互通
version: "3.9"

networks:
  frontend:
  backend:

services:

  chatgpt-web:
    image: jiajiangtao122/chatgpt-web
    container_name: chatgpt-web
    networks:
       backend:
        aliases:
          - chatgpt-web.serv
       frontend:
        aliases:
          - chatgpt-web.app
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.24
    container_name: nginx
    networks:
       frontend:
        aliases:
          - nginx.app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - ./chatgpt-web:/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chatgpt-web

  mysql:
    image: bitnami/mysql:5.7
    container_name: mysql
    networks:
      backend:
        aliases:
          - mysql.serv
    volumes:
      - ./mysql/data:/bitnami/mysql/data
    environment:
      MYSQL_MASTER_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
    ports:
      - "3306:3306"
